package prakikum3_gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Random;
import java.util.stream.IntStream;

/**
 *
 * @author abi
 */
public class RamalDemo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RamalDemo.class.getName());

    /**
     * Creates new form RamalDemo
     */
    public RamalDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaHasilRamal = new javax.swing.JTextArea();
        btnRamal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        kodam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(460, 350));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 13)); // NOI18N
        jLabel1.setText("Nama Anda");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 1, 13)); // NOI18N
        jLabel2.setText("Hasil Ramalan");

        txaHasilRamal.setColumns(20);
        txaHasilRamal.setRows(5);
        jScrollPane1.setViewportView(txaHasilRamal);

        btnRamal.setText("Ramal");
        btnRamal.setPreferredSize(new java.awt.Dimension(100, 28));
        btnRamal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRamalActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.setPreferredSize(new java.awt.Dimension(100, 28));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        kodam.setText("cek khodam");
        kodam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(kodam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRamal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(kodam))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRamal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        btnKeluar.addActionListener((ActionEvent ae) -> {
                System.exit(0);
        });        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnRamalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRamalActionPerformed
        int pjgNama, kodeRamal;


        String hasilRamal;


        pjgNama = txtNama.getText().length();


        kodeRamal = pjgNama % 6;


        switch (kodeRamal) {
            case 0:
                hasilRamal = "Ampun deh...\nAnda ditakdirkan untuk sengsara. " +
                             "Apapun yang Anda upayakan tidak akan berhasil. Saya " +
                             "ikut prihatin untuk Anda.";
                break;
            case 1:
                hasilRamal = "Aduh...\nSepertinya hidup Anda ditakdirkan " +
                             "untuk susah. Tabah ya dalam menghadapinya...";
                break;
            case 2:
                hasilRamal = "Wah...\nAkan ada banyak masalah yang muncul " +
                             "dalam kehidupan Anda. Rajin berdoa ya...";
                break;
            case 3:
                hasilRamal = "Hmmm...\nAnda cukup beruntung tapi Anda harus " +
                             "bekerja keras untuk mendapatkannya.";
                break;
            case 4:
                hasilRamal = "Selamat...\nAnda benar-benar ditakdirkan " +
                             "untuk beruntung. Jangan lupa bagi-bagi ke lain ya.";
                break;
            default:
                hasilRamal = "Hmmm...\nMagf... Anda tidak bisa saya ramal! " +
                                "Jangan-jangan Anda berasal dari dunia lain!";
                break;
        }
        txaHasilRamal.setForeground(Color.blue);
        txaHasilRamal.setEditable(false);
        txaHasilRamal.setLineWrap(true);
        txaHasilRamal.setWrapStyleWord(true);
        
        txaHasilRamal.setText(hasilRamal);
        
        
    }//GEN-LAST:event_btnRamalActionPerformed

    private void kodamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodamActionPerformed
        String[] namaKhodam = {
                "Bayu Petir Gelap",
                "Ratu Nyala Malam",
                "Arka Hantu Senja",
                "Sang Penjaga Bayangan",
                "Naga Bisu Merah",
                "Putri Kabut Biru",
                "Jubah Hitam Berbisik",
                "Mata Ember Kuno",
                "Penunggu Lembah Sunyi",
                "Putra Awan Kelabu",
                "Raja Lumpur Purba",
                "Hantu Seribu Tanduk",
                "Si Merpati Kegelapan",
                "Pelindung Bintang Mati",
                "Sang Penyusup Angin",
                "Siluman Embun Senja",
                "Rantai Api Tak Bernama",
                "Penjaga Batu Senandung",
                "Roh Laut Bergelora",
                "Sang Arwah Merah",
                "Bagas Rotasi"
                
        };
        Random rd = new Random();
        int rdk = rd.nextInt(namaKhodam.length);
        txaHasilRamal.setText(namaKhodam[rdk]);
        
    }//GEN-LAST:event_kodamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RamalDemo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRamal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kodam;
    private javax.swing.JTextArea txaHasilRamal;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
