
package view;

import Model.Mahasiswa;
import java.awt.event.ActionEvent;
import javax.swing.table.TableColumn;
import stmik.KoneksiDB;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Arrays;

/**
 *
 * @author abi
 */
public class MahasiswaForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MahasiswaForm.class.getName());
    Mahasiswa model = new Mahasiswa();
    /** Creates new form MahasiswaForm */
    public MahasiswaForm() {
        initComponents();
        
        tabelMahasiswa.setModel(model);
        setKolomTabel();
        tampilData();
        isiComboBox();
    }
    
    
    public void isiComboBox(){
        cboJurusan.removeAllItems();
        
        cboJurusan.addItem("SI");
        cboJurusan.addItem("KA");
    }
    
    public void kosongkanIsian(){
        txtNIM.setText("");
        txtNama.setText("");
        txtTmpLahir.setText("");
        
        calTglLahir.setDate(null);
        cboJurusan.setSelectedIndex(0);
    }
    
    public void setKolomTabel(){
        TableColumn column = null;
        for(int i = 0;i<4;i++){
            column = tabelMahasiswa.getColumnModel().getColumn(i);
            switch(i){
                case 0 -> column.setPreferredWidth(60);
                case 1 -> column.setPreferredWidth(100);
                case 2 -> column.setPreferredWidth(100);
                case 3 -> column.setPreferredWidth(80);
                case 4 -> column.setPreferredWidth(20);
            }
        }
    }
    
    public void tampilData(){
        try{
            Connection c = KoneksiDB.getConnection();
            Statement s = c.createStatement();
            
            String query = "SELECT * FROM tbMahasiswa";
            ResultSet r = s.executeQuery(query);
            
            while(r.next()){
                
                Object[] o = new Object[5];
                o[0] = r.getString("nim");
                o[1] = r.getString("nama");
                o[2] = r.getString("tmpLahir");
                o[3] = r.getString("tglLahir");
                o[4] = r.getString("jurusan");
                
                model.addRow(Arrays.asList(o));
            }
        } catch (SQLException e){
            e.printStackTrace();
            System.out.println("Error while showing data");
        }
    }
    
    private java.sql.Date konversiDate(java.util.Date utilDate){
        java.sql.Date sqlDate = null;
        if(utilDate != null)
            sqlDate = new java.sql.Date(utilDate.getTime());
        return sqlDate;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTmpLahir = new javax.swing.JTextField();
        cboJurusan = new javax.swing.JComboBox<>();
        calTglLahir = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Tempat Lahir");

        jLabel4.setText("Tanggal Lahir");

        jLabel5.setText("Jurusan");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelMahasiswa);

        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });

        txtTmpLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTmpLahirActionPerformed(evt);
            }
        });

        cboJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNIM)
                                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(calTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(cboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTmpLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(calTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nim = txtNIM.getText();
        String nama = txtNama.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        if(calTglLahir.getDate() == null) return;
        
        String tglLahir = sdf.format(calTglLahir.getDate());
        String tmpLahir = txtTmpLahir.getText();
        String jurusan = cboJurusan.getSelectedItem().toString();
        
        try{
            Connection c = KoneksiDB.getConnection();
            String query = "INSERT INTO tbMahasiswa VALUES(?,?,?,?,?)";
            
            PreparedStatement p = c.prepareStatement(query);
            
            p.setString(1,nim);
            p.setString(2,nama);
            p.setString(3,tmpLahir);
            p.setDate(4,konversiDate(calTglLahir.getDate()));
            p.setString(5,jurusan);
            
            p.executeUpdate();
            p.close();
        } catch (SQLException e ){
            e.printStackTrace();
            System.out.println("Error while adding data");
          
        }
        model.addRow(Arrays.asList(nim,nama,tmpLahir,tglLahir,jurusan));
        
        tabelMahasiswa.setModel(model);
        
        setKolomTabel();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MahasiswaTable tableForm = new MahasiswaTable();
        tableForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIMActionPerformed

    private void txtTmpLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTmpLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTmpLahirActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int index = tabelMahasiswa.getSelectedRow();
        
        if(index == -1) return;
        
        String nim = txtNIM.getText();
        String nama = txtNama.getText();
        String tmpLahir = txtTmpLahir.getText();
        
        if(calTglLahir.getDate() == null) return;
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tglLahir = sdf.format(calTglLahir.getDate());
        String jurusan = cboJurusan.getSelectedItem().toString();
        
        try{
            Connection c = KoneksiDB.getConnection();
            String query = """
                           UPDATE tbMahasiswa 
                           SET nim = ?, nama = ?,tmpLahir = ?,tglLahir = ?,jurusan = ? 
                           WHERE nim = ?
                           """;
            PreparedStatement p = c.prepareStatement(query);
            
            p.setString(1,nim);
            p.setString(2,nama);
            p.setString(3,tmpLahir);
            p.setDate(4,konversiDate(calTglLahir.getDate()));
            p.setString(5,jurusan);
            p.setString(6,nim);
           
            
            
            p.executeUpdate();
            p.close();
        } catch(SQLException e){
            e.printStackTrace();
            System.out.println("Error when Changing data");
        } finally{
            model.setValueAt(nim,index,0);
            model.setValueAt(nama,index,1);
            model.setValueAt(tmpLahir,index,2);
            model.setValueAt(tglLahir,index,3);
            model.setValueAt(jurusan,index,4);
            
            tabelMahasiswa.setModel(model);
            
            setKolomTabel();
        }
        
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = tabelMahasiswa.getSelectedRow();
        
        if(index == -1) return;
        
        String nim = (String) model.getValueAt(index, 0);
        
        try{
            Connection c = KoneksiDB.getConnection();
            String query = "DELETE FROM tbMahasiswa WHERE nim =?";
            
            PreparedStatement p = c.prepareStatement(query);
            p.setString(1,nim);
            p.executeUpdate();
            p.close();
        } catch( SQLException e){
            e.printStackTrace();
            System.out.println("Error when deleting data");
        } finally{
            model.removeRow(index);
            
            tabelMahasiswa.setModel(model);
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        // TODO add your handling code here:
        int index = tabelMahasiswa.getSelectedRow();
        
        if(index == -1) return;
        
        String nim = (String) tabelMahasiswa.getValueAt(index, 0);
        String nama = (String) tabelMahasiswa.getValueAt(index, 1);
        String tmpLahir = (String) tabelMahasiswa.getValueAt(index, 2);
        String tglLahir = (String) tabelMahasiswa.getValueAt(index, 3);
        String jurusan = (String) tabelMahasiswa.getValueAt(index, 4);
        
        txtNIM.setText(nim);
        txtNama.setText(nama);
        txtTmpLahir.setText(tmpLahir);
        
        try{
            java.util.Date tanggal = new SimpleDateFormat("yyyy-MM-dd")
            .parse(tglLahir);
            calTglLahir.setDate(tanggal);
        }catch(Exception e){
            e.printStackTrace();
            System.out.println("Error while showing Date");
        }
        
        if(jurusan.equals("SI")){
            cboJurusan.setSelectedIndex(0);
        } else{
            cboJurusan.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MahasiswaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private com.toedter.calendar.JDateChooser calTglLahir;
    private javax.swing.JComboBox<String> cboJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTmpLahir;
    // End of variables declaration//GEN-END:variables

}
